# Generated by Django 3.0.11 on 2021-02-11 07:18

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0032_delete_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A chef with that username already exists.'}, max_length=150, unique=True, validators=[
                 django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('youtube_video', models.URLField(blank=True, null=True)),
                ('instagram_account', models.URLField(blank=True, null=True)),
                ('facebook_account', models.URLField(blank=True, null=True)),
                ('twitter_account', models.URLField(blank=True, null=True)),
                ('tiktok_account', models.URLField(blank=True, null=True)),
                ('brands', models.ManyToManyField(
                    blank=True, related_name='chefs', to='core.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
